version: '3.1'

services:
  php:
    build: .
    restart: always
    depends_on:
        - db
    volumes:
        - '.:/app'
    ports:
        - 9991:8989

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "36001:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
